name: Create Azure resources and deploy app
on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
      - name: Create resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ vars.AZURE_RG }}
          template: ${{ github.workspace }}/config/main.bicep
          parameters: 'namePrefix=${{ vars.AZURE_PREFIX }}'
          failOnStdErr: false

      # Set MONGODB_URI as an environment variable
      - name: Set MONGODB_URI
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV

      # Build and push image to Azure Container Registry
      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ vars.AZURE_PREFIX }}pets:${{ github.sha }} --registry ${{ vars.AZURE_PREFIX }}acr --file Dockerfile .

      # Deploy to Azure Container Apps
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: ${{ vars.AZURE_PREFIX }}acr
          acrUsername: ${{ secrets.REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: ${{ vars.AZURE_PREFIX }}pets
          resourceGroup: ${{ vars.AZURE_RG }}
          imageToDeploy: ${{ vars.AZURE_PREFIX }}acr.azurecr.io/${{ vars.AZURE_PREFIX }}pets:${{ github.sha }}
          environmentVariables: MONGODB_URI=${{ secrets.MONGODB_URI }}